### ISSUE TITLE
Mismerge

### ISSUE THREAD

**Issue by RogueMaster** [armixz/Flipper-Zero-Programmer-Calculator#1]
You still have lots of mis-merged content... [example](https://github.com/armixz/Flipper-Zero-Programmer-Calculator/blob/main/input_handling.c#L104)

**Comment by armixz** [comment]
Thank you. Fixed under [commit](https://github.com/armixz/Flipper-Zero-Programmer-Calculator/commit/207bb11656913dfc6441438b597d95634ea8cb05)
